---
title: "Luquillo LTER"
authors: Wylie Hampson, Allie Cole, Grace Lewin, Charles Hendrickson
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(lubridate)
library(janitor)
library(patchwork)
```

## Import the data

```{r}
# PRM Data set
prm_data <- read_csv("/courses/EDS214/team_basset_hound/data/RioMameyesPuenteRoto.csv", na = "-9999")

# BQ1 Data set
bq1_data <- read_csv("/courses/EDS214/team_basset_hound/data/QuebradaCuenca1-Bisley.csv", na = "-9999")

# BQ2 Data set
bq2_data <- read_csv("/courses/EDS214/team_basset_hound/data/QuebradaCuenca2-Bisley.csv", na = "-9999")

# BQ3 Data set
bq3_data <- read.csv("/courses/EDS214/team_basset_hound/data/QuebradaCuenca3-Bisley.csv", na = "-9999")

```

## Cleaning data

```{r}
#Checked the meta data to make sure units are good 
prm_subset <- prm_data %>% 
  clean_names() %>% 
  select(sample_date, sample_id, no3, k) %>% 
  mutate(sample_date = lubridate::mdy(sample_date))

bq1_subset <- bq1_data %>% 
  clean_names() %>% 
  select(sample_date, sample_id, no3, k) %>% 
  mutate(sample_date = mdy(sample_date))

bq2_subset <-  bq2_data %>% 
  clean_names() %>% 
  select(sample_date, sample_id, no3, k) %>% 
  mutate(sample_date = mdy_hm(sample_date))

bq3_subset <- bq3_data %>% 
  clean_names() %>% 
  select(sample_date, sample_id, no3, k) %>% 
  mutate(sample_date = mdy(sample_date))

```

## Join the separate data frames

```{r}
full_df <- full_join(prm_subset, bq1_subset) %>% 
  full_join(bq2_subset) %>% 
  full_join(bq3_subset) %>% 
  filter(year(sample_date) >= 1988 & year(sample_date) <= 1995)
```

## Plot the data

```{r}
plot_k <- ggplot(data = full_df, aes(x = sample_date, y = k)) +

  geom_line(aes(color = sample_id, linetype = sample_id), size = 0.3) + 
  geom_vline(xintercept = as.POSIXct(as.Date("1989-09-10")), linetype = 4) + 
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        panel.background = element_blank(), 
        panel.grid.major = element_line(color = "light grey")) +
  labs(y = "K mg l\u207b\u00b9", 
       color = "Site",
       linetype = "Site")


plot_no3 <- ggplot(data = full_df, aes(x = sample_date, y = no3)) +
  geom_line(aes(color = sample_id, linetype = sample_id), show.legend = FALSE, size = 0.3) + 
  geom_vline(xintercept = as.POSIXct(as.Date("1989-09-10")), linetype = 4) +
  labs(x = "Date", 
       y = "NO\u2083\u2010N \u00b5g l\u207b\u00b9") + 
  theme(panel.background = element_blank(), 
        panel.grid.major = element_line(color = "light grey")) 
  

final_plot <- (plot_k / plot_no3) 

ggsave(here::here("figs", "final_plot.jpg"), plot = final_plot, height = 4, width = 7)
  
```


